# -*- coding: utf-8 -*-
"""ml_project_KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WGiVal9OK4FQHJ80QSJgEFrxW3zDodia
"""

#KNN
from sklearn.model_selection import train_test_split
dataset="/content/drive/MyDrive/ML_project_Data/our_features_3_sec.csv"
data = pd.read_csv(dataset)
#data = data.drop(columns=['filename'])
data = data.drop(columns=['filename','chroma_stft_var', 'rmse_var', 'spectral_centroid_var', 'spectral_bandwidth_var', 'rolloff_var', 'zero_crossing_rate_var', 'mfcc1_var', 'mfcc2_var', 'mfcc3_var', 'mfcc4_var', 'mfcc5_var', 'mfcc6_var', 'mfcc7_var', 'mfcc8_var', 'mfcc9_var', 'mfcc10_var', 'mfcc11_var', 'mfcc12_var', 'mfcc13_var', 'mfcc14_var', 'mfcc15_var', 'mfcc16_var', 'mfcc17_var', 'mfcc18_var', 'mfcc19_var', 'mfcc20_var'])
data['label'] = pd.factorize(data['label'])[0]
y=data['label']
data.drop(columns=['label'])
X=data
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=5, weights='distance')
neigh.fit(X_train, Y_train)

train_preds = neigh.predict(X_train)
train_acc = np.sum(train_preds == Y_train)
train_acc = train_acc / len(Y_train)


test_preds = neigh.predict(X_test)
test_acc = np.sum(test_preds == Y_test)
test_acc = test_acc / len(Y_test)

print('Train acc: ',train_acc, ' Test acc: ' test_acc)

#Plot confusion matrix for KNN
import matplotlib.pyplot as plt  
from sklearn.metrics import plot_confusion_matrix
plot_confusion_matrix(neigh, X_test, Y_test)  
plt.show()